#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-zabbix_api
Version  : 0.5.4
Release  : 2
URL      : https://files.pythonhosted.org/packages/e3/ed/2092731880f0de5b07067fc446dc0fc5166f2ee98018b6d524cd3e28a69d/zabbix-api-0.5.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/e3/ed/2092731880f0de5b07067fc446dc0fc5166f2ee98018b6d524cd3e28a69d/zabbix-api-0.5.4.tar.gz
Summary  : Zabbix API
Group    : Development/Tools
License  : LGPL-2.1
Requires: pypi-zabbix_api-python = %{version}-%{release}
Requires: pypi-zabbix_api-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Please note that the Zabbix API is still in a draft state,
        and subject to change.
        
        Implementations of the Zabbix API in other languages may
        be found on the wiki.
        
        Zabbix 1.8, 2.0, 2.2, 2.4, 3.0 and 3.2 are supported.
        Python 2 and 3 are supported.
        
        Future versions must be supported too, if there is no deep changes.

%package python
Summary: python components for the pypi-zabbix_api package.
Group: Default
Requires: pypi-zabbix_api-python3 = %{version}-%{release}

%description python
python components for the pypi-zabbix_api package.


%package python3
Summary: python3 components for the pypi-zabbix_api package.
Group: Default
Requires: python3-core
Provides: pypi(zabbix_api)

%description python3
python3 components for the pypi-zabbix_api package.


%prep
%setup -q -n zabbix-api-0.5.4
cd %{_builddir}/zabbix-api-0.5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639050468
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
